# Generated by Django 4.2.19 on 2025-02-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_icecream_output_order_icecream_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
